services:
  cassandra:
    container_name: cassandra
    image: 'cassandra:latest'
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042:9042'
    expose:
      - '9042'
    networks:
      - myNetwork
  backend:
    container_name: xyu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - myNetwork
    depends_on:
      - cassandra
    restart: always
networks:
  myNetwork:
    driver: bridge
