services:
  cassandra:
    container_name: cassandra
    image: 'cassandra:latest'
    environment:
      - 'CASSANDRA_DC=datacenter1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042:9042'
    expose:
      - '9042'
    networks:
      - myNetwork
  backend:
    container_name: xyu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - myNetwork
    depends_on:
      - cassandra
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'zxc'
    volumes:
      - ./script:/docker-entrypoint-initdb.d
    ports:
      - "5430:5432"

networks:
  myNetwork:
    driver: bridge
