services:
  cassandra:
    container_name: cassandra
    image: 'cassandra:latest'
    environment:
      - 'CASSANDRA_DC=datacenter1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
    ports:
      - '9042:9042'
    expose:
      - '9042'
    networks:
      - myNetwork

  actual:
    container_name: actual
    image: postgres:latest
    environment:
      POSTGRES_DB: "actualdb"
      POSTGRES_USER: "actualdbuser"
      POSTGRES_PASSWORD: "zxc"
    ports:
      - "5431:5432"
  archive:
    container_name: archive
    image: postgres:latest
    environment:
      POSTGRES_DB: "archivedb"
      POSTGRES_USER: "archivedbuser"
      POSTGRES_PASSWORD: "zxc"
    ports:
      - "5430:5432"
  db:
    container_name: databases
    build:
      context: ./databases
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - myNetwork
    depends_on:
      - zookeeper
  backend:
    container_name: xyu
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - myNetwork
    depends_on:
      - cassandra
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  myNetwork:
    driver: bridge
